# Chem121 Intro to CompChem

## Matrix Algebra

In this section we look at matrix algebra and some of its common properties.  We will also see how operations involving matrices are connected to linear systems of equations.

A **matrix** a is two-dimensional array of numbers.  When we do computations with matrices using NumPy, we will be using arrays just as we did before.  Let's write down some of examples of matrices and give them names.

$$
\begin{equation}
A = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] \hspace{1cm} 
B = \left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right] \hspace{1cm}
C = \left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right] \hspace{1cm}
D = \left[ \begin{array}{r} 2 \\ 6 \end{array}\right]
\end{equation}
$$

When discussing matrices it is common to talk about their dimensions, or shape, by specifying the number of rows and columns.  The number of rows is usually listed first.  For our examples, $A$ and $C$ are $2\times 2$ matrices, $B$ is a $2 \times 3$ matrix, and $D$ is a $2 \times 1 $ matrix.  Matrices that have only 1 column, such as $D$, are commonly referred to as **vectors**.  We will adhere to this convention as well, but do be aware that when we make statements about matrices, we are also making statements about vectors even if we don't explicitly mention them.  We will also adopt the common convention of using uppercase letters to name matrices.

It is also necessary to talk about the individual entries of matrices.  The common notation for this is a lowercase letter with subscripts to denote the position of the entry in the matrix.  So $b_{12}$ refers to the 0 in the first row and second column of the matrix $B$.  If we are talking about generic positions, we might use variables in the subscripts, such as $a_{ij}$.

Let's create these matrices as NumPy arrays before further discussion.

In [24]:
import numpy as np

A = np.array([[1, 3],[2,1]])

In [27]:
A[0,1]

3

In [28]:
import numpy as np
A = np.array([[1, 3],[2,1]])
B = np.array([[3, 0, 4],[-1, -2, 1]])
C = np.array([[-2, 1],[4, 1]])
D = np.array([[2],[6]])
print(A)

[[1 3]
 [2 1]]


In [29]:
B = np.array([[3, 0, 4],[-1, -2, 1]])

In [31]:
B.shape

(2, 3)

It will be useful for us to access the dimensions of our arrays.  When the array is created, this information gets stored as part of the array object and can be accessed with a method called $\texttt{shape}$.  If $\texttt{B}$ is an array, the object $\texttt{B.shape}$ is itself an array that has two entries.  The first (*with index 0!*) is the number of rows, and the second (*with index 1!*) is the number of columns.

In [2]:
print("Array B has",B.shape[0],"rows.")
print("Array B has",B.shape[1],"columns.")      

Array B has 2 rows.
Array B has 3 columns.


### Identity matrices

An **identity matrix** is a square matrix that behaves similar to the number 1 with respect to ordinary multiplication.  Identity matrices, labeled with $I$, are made up of ones along the main diagonal, and zeros everywhere else.  Below is the $4 \times 4$ version of $I$.

$$
\begin{equation}
I = \left[ \begin{array}{ccc} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0\\ 0 & 0 & 0 & 1 \end{array}\right]
\end{equation}
$$

If $A$ is any other $4 \times 4$ matrix, multiplication with $I$ will produce $A$.  Furthermore it doesn't matter in this case which order the multiplication is carried out.

$$
\begin{equation}
AI = IA = A
\end{equation}
$$

The NumPy function $\texttt{eye}$ generates an identity matrix of the specified size.  Note we only need to provide $\texttt{eye}$ with one parameter since the identity matrix must be square.  We show here the product of $I$ with a random $5\times 5$ matrix.  

In [11]:
I5 = np.eye(5)
print(I5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
B = np.array([[3, 0, 4],[-1, -2, 1]])
B

array([[ 3,  0,  4],
       [-1, -2,  1]])

In [40]:
A @ A

array([[7, 6],
       [4, 7]])

In [41]:
np.dot(A, A)

array([[7, 6],
       [4, 7]])

In [39]:
A * A

array([[1, 9],
       [4, 1]])

### Operations on matrices

There are three algebraic operations for matrices that we will need to perform.  For our definitions let us suppose that $A$ and $C$ are $m \times n$ matrices, $B$ is an $n \times k$ matrix, and $c$ is a number.  When discussing algebra involving matrices and numbers, the numbers are usually referred to as **scalars**. 

1. A matrix of any shape can be multiplied by a scalar.  The result is that all entries are multiplied by that scalar.  Using the subscript notation, we would write

$$
(cA)_{ij} = ca_{ij}
$$

2. Two matrices that *have the same shape* can be added.  The result is that all corresponding entries are added.

$$
(A+C)_{ij} = a_{ij} + c_{ij}
$$

3. If the number of columns of matrix $A$ is equal to the number of rows of matrix $B$, the matrices can be multiplied in the order $A$, $B$.  The result will be a new matrix $AB$, that has the same number of rows as $A$ and the same number of columns as $B$.  The entries $(AB)_{ij}$ will be the following combination of the entries of row $i$ of $A$ and column $j$ of $B$.

$$
(AB)_{ij} = \sum_{k=1}^n a_{ik}b_{kj}
$$

The last operation, known as **matrix multiplication**, is the most complex and least intuitive of the three.  No doubt this last formula is a bit intimidating the first time we read it.  Let's give some examples to clarify.

1.  The multiplication of a number and a matrix:

$$
\begin{equation}
3A = 3\left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] 
= \left[ \begin{array}{rr} 3 & 9 \\ 6 & 3 \end{array}\right]
\end{equation}
$$

2. The sum of two matrices of the same shape:

$$
\begin{equation}
A + C = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right] + 
\left[ \begin{array}{rr} -2 & 1 \\ 4 & 1 \end{array}\right] 
= \left[ \begin{array}{rr} -1 & 4 \\ 6 & 2 \end{array}\right]
\end{equation}
$$

3.  The multiplication of two matrices:

$$
\begin{equation}
AB = \left[ \begin{array}{rr} 1 & 3 \\ 2 & 1 \end{array}\right]
\left[ \begin{array}{rrr} 3 & 0 & 4 \\ -1 & -2 & 1 \end{array}\right]
 = \left[ \begin{array}{rrr} 0 & -6 & 7  \\  5 & -2 & 9  \end{array}\right]
 \end{equation}
$$
 
To clarify what happens in the  matrix multiplication, lets calculate two of the entries in detail.

$$
\begin{eqnarray*}
(AB)_{12} & = & 1\times 0 + 3 \times (-2) = -6 \\
(AB)_{23} & = & 2 \times 4 + 1 \times 1 = 9
\end{eqnarray*}
$$

These matrix operations are all built into NumPy, but we have to use the symbol $\texttt{@}$ instead of $\texttt{*}$ for matrix multiplication.

In [7]:
print("A:\n", A, '\n')

print("B:\n", B, '\n')

print("C:\n", C, '\n')

A:
 [[1 3]
 [2 1]] 

B:
 [[ 3  0  4]
 [-1 -2  1]] 

C:
 [[-2  1]
 [ 4  1]] 



In [10]:
print(3*A,'\n')
print(A+C,'\n')
print(A@B,'\n')
print(A*C)

[[3 9]
 [6 3]] 

[[-1  4]
 [ 6  2]] 

[[ 0 -6  7]
 [ 5 -2  9]] 

[[-2  3]
 [ 8  1]]


### Properties of matrix operations

It is useful to observe that some common algebraic properties hold true for matrix multiplication.  Let $A$, $B$, and $C$ be matrices, and $k$ be a scalar.  The associative and distributive properties stated here hold for matrix multiplication.

$$
\begin{equation}
k(A+B) = kA + kB
\end{equation}
$$

$$
\begin{equation}
C(A+B) = CA + CB
\end{equation}
$$

$$
\begin{equation}
A(BC) = (AB)C
\end{equation}
$$

These statements only make sense of course if the matrices have dimensions that allow for the operations.

It is also worth noting that the commutative property does not generally hold for matrix multiplication.  Suppose for example that $A$ and $B$ are both $3\times 3$ matrices.  It is **not true in general** that $AB = BA$.  One example with random matrices is enough to prove this point.

In [4]:
A = np.random.randint(-5,5,size=(3,3))
B = np.random.randint(-5,5,size=(3,3))

print(A@B)
print('\n')
print(B@A)

[[ 35 -11 -14]
 [-28  -7   7]
 [  3  22  13]]


[[ 13  11  -4]
 [  7  44   4]
 [  8 -21 -16]]


### Matrix transposes

Another common idea that we will find useful is that of the matrix transpose.  The **transpose** of a matrix $A$ is another matrix, $A^T$, defined so that its columns are the rows of $A$.  To build $A^T$, we simple swap the row index with the column index for every entry, $a^T_{ij} = a_{ji}$.  Two examples should be enough to clarify this definition.

$$
\begin{equation}
A = \left[ \begin{array}{rrr} 5 & 4 & 0 \\ 1 & 8 & 3 \\ 6 & 7 & 2\end{array}\right] \hspace{1cm}
A^T = \left[ \begin{array}{rrr} 5 & 1 & 6 \\ 4 & 8 & 7 \\ 0 & 3 & 2\end{array}\right] \hspace{1cm}
\end{equation}
$$

$$
\begin{equation}
B = \left[ \begin{array}{rrr} 1 & 2 & 7 & 0 \\ 3 & 1 & 5 & 2 \\ 4 & 9 & 8 & 6\end{array}\right] \hspace{1cm}
B^T = \left[ \begin{array}{rrr} 1 & 3 & 4 \\ 2 & 1 & 9 \\ 7 & 5 & 8 \\ 0 & 2 & 6\end{array}\right] \hspace{1cm}
\end{equation}
$$


NumPy array objects have a method named $\texttt{transpose}$ for this purpose.

In [44]:
A = np.array([[5, 4, 0],[1, 8, 3]])

In [46]:
A.transpose().shape

(3, 2)

In [5]:
A = np.array([[5, 4, 0],[1, 8, 3],[6, 7, 2]])

## Note that the tranpose method must be called with (), the same as a function with no arguments.
A_T = A.transpose()

print(A)
print('\n')
print(A_T)

[[5 4 0]
 [1 8 3]
 [6 7 2]]


[[5 1 6]
 [4 8 7]
 [0 3 2]]


When a matrix $A$ is equal to its own transpose, it has the property of being symmetric across its main diagonal. For this reason a matrix $A$ is said to be **symmetric** if $A = A^T$. Equivalently, we can say that $A$ is symmetric if $a_{ij} = a_{ji}$ for every entry $a_{ij}$ in the matrix.  The matrix $P$ below is one such example.

$$
\begin{equation}
P = \left[ \begin{array}{rrr} 1 & 0 & 6 \\ 0 & 3 & 5 \\ 6 & 5 & -2\end{array}\right] \hspace{1cm}
\end{equation}
$$

Similarly, we say that a matrix $A$ is **skew-symmetric** if $A^T = -A$ (equivalently $a_{ij} = -a_{ji}$ for every entry $a_{ij}$ in $A$). The matrix $Q$ below is a skew-symmetric matrix.

$$
\begin{equation}
Q = \left[ \begin{array}{rrr} 0 & 1 & -4 \\ -1 & 0 & 5 \\ 4 & -5 & 0\end{array}\right] \hspace{1cm}
\end{equation}
$$


### Application to linear systems

A very important example of matrix multiplication is that where a known matrix multiplies an *unknown* vector to produce a known vector.  If we let $A$ be the known matrix, $B$ be the known vector, and $X$ be the unknown vector, we can write the matrix equation $AX=B$ to describe this scenario.  Let's write a specific example.

$$
\begin{equation}
A= \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right] \hspace{1cm}
X= \left[ \begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array}\right] \hspace{1cm}
B= \left[ \begin{array}{r} 0 \\ 10 \\ 7 \\ 4  \end{array}\right] \hspace{1cm}
\end{equation}
$$

$$
\begin{equation}
AX = \left[ \begin{array}{rrr} 1 & 3 & -2 \\ 5 & 2 & 0 \\ 4 & 2 & -1 \\ 2 & 2 & 0 \end{array}\right]
\left[ \begin{array}{r} x_1 \\ x_2 \\ x_3 \end{array}\right]=
\left[ \begin{array}{r} 0\\ 10 \\ 7 \\ 4  \end{array}\right]= B
\end{equation}
$$

If we apply the definition of matrix multiplication we see that this single matrix equation $AX=B$ in fact represents a system of linear equations.

$$
\begin{eqnarray*}
x_1 + 3x_2 - 2x_3 & = & 0\\
5x_1 + 2x_2 \quad\quad & = & 10 \\
4x_1 + 2x_2 - x_3 & = & 7 \\
2x_1 + 2x_2 \quad\quad & = & 4
\end{eqnarray*}
$$

In this context, the matrix $A$ is known as the **coefficient matrix**.

In [47]:
A = np.array([[1, 3, -2], [5, 2, 0], [4, 2, -1], [2, 2, 0]])
B = np.array([0, 10, 7, 4])

In [48]:
from scipy.linalg import inv

In [49]:
A_inv = inv(A)

ValueError: expected square matrix

In [50]:
import numpy as np
from numpy.linalg import solve


X = solve(A, B)

LinAlgError: Last 2 dimensions of the array must be square

In [51]:
from scipy.linalg import solve
A = np.array([[1, 3, -2], [5, 2, 0], [4, 2, -1]])
B = np.array([0, 10, 7])
X = solve(A, B)
print(X)

[2.00000000e+00 5.12410627e-16 1.00000000e+00]


In [53]:
A_inv = inv(A)
A_inv

array([[-0.22222222, -0.11111111,  0.44444444],
       [ 0.55555556,  0.77777778, -1.11111111],
       [ 0.22222222,  1.11111111, -1.44444444]])

In [54]:
A_inv @ B

array([2.0000000e+00, 8.8817842e-16, 1.0000000e+00])

In [55]:
from scipy.linalg import pinv

In [57]:
A = np.array([[1, 3, -2], [5, 2, 0], [4, 2, -1], [2, 2, 0]])
B = np.array([0, 10, 7, 4])

In [58]:
pinv(A) @ B

array([2.0000000e+00, 4.4408921e-16, 1.0000000e+00])

### Solving linear equations using matrix inverse

If $A$, $B$, and $X$ were instead only numbers, we would recognize immediately that the way to solve for $X$ is to divide both sides of the equation by $A$, so long as $A\neq 0$.  The natural question to ask about the system is *Can we define matrix division?*

The answer is *Not quite.*  We can make progress though by understanding that in the case that $A$,$B$, and $X$ are numbers, we could also find the solution by multiplying by $1/A$.  This subtle distinction is important because it means that we do not need to define division.  We only need to find the number, that when multiplied by $A$ gives 1.  This number is called the multiplicative inverse of $A$ and is written as $1/A$, so long as $A\neq 0$.

We can extend this idea to the situation where $A$, $B$, and $X$ are matrices.  In order to solve the system $AX=B$, we want to multiply by a certain matrix, that when multiplied by $A$ will give the identity matrix $I$.  This matrix is known as the **inverse matrix**, and is given the symbol $A^{-1}$.

If $A$ is a square matrix we define $A^{-1}$ (read as "A inverse") to be the matrix such that the following are true.

$$
A^{-1}A = I \hspace{3cm}AA^{-1} = I
$$

Notes about inverse matrices:

1. The matrix must be square in order for this definition to make sense.  If $A$ is not square, it is impossible for both 
$A^{-1}A$ and $AA^{-1}$ to be defined.
2. Not all matrices have inverses.  Matrices that do have inverses are called **invertible** matrices.  Matrices that do not have inverses are called **non-invertible**, or **singular**, matrices.
3. If a matrix is invertible, its inverse is unique.

Now *if we know* $A^{-1}$, we can solve the system $AX=B$ by multiplying both sides by $A^{-1}$.

$$
A^{-1}AX = A^{-1}B
$$

Then $A^{-1}AX = IX = X$, so the solution to the system is $X=A^{-1}B$.  

In [21]:
from scipy.linalg import inv
A = np.array([[1, 3, -2], [5, 2, 0], [4, 2, -1]])
B = np.array([0, 10, 7])
X = inv(A) @ B
print(X)

[2.0000000e+00 8.8817842e-16 1.0000000e+00]


In [22]:
A = np.array([[1, 3, -2], [5, 2, 0], [4, 2, -1], [2, 2, 0]])
B = np.array([0, 10, 7, 4])
inv(A)

ValueError: expected square matrix

In [23]:
from scipy.linalg import pinv
A = np.array([[1, 3, -2], [5, 2, 0], [4, 2, -1]])
B = np.array([0, 10, 7])
X = pinv(A) @ B
print(X)

[ 2.00000000e+00 -5.55111512e-15  1.00000000e+00]


### What does it mean?

The set of equations:
$$
\begin{eqnarray*}
x_1 + 3x_2 - 2x_3 & = & 0\\
5x_1 + 2x_2 \quad\quad & = & 10 \\
4x_1 + 2x_2 - x_3 & = & 7 \\
2x_1 + 2x_2 \quad\quad & = & 4
\end{eqnarray*}
$$
is over-determined. The Pseudo-inverse method gives the best least-square fit.

## Eigenvalues and eigenvectors

Given $A \in \mathbb{R}^{n\times n}$, $\lambda$ is the **eigenvalue** of $A$, if there is a non-zero vector $x$, the corresponding **eigenvector**, if the following is true:

$Ax = \lambda x, x \neq 0$

Formally, given a square matrix $A \in \mathbb{R}^{n\times n}$, we say that $\lambda \in \mathbb{C}$ is an **eigenvalue** of $A$ and $x \in \mathbb{C}^n$ is the corresponding **eigenvector**.

Intuitively, this definition means that multiplying $A$ by the vector $x$ results in a new vector that points in the same direction as $x$, but is scaled by a factor $\lambda$.

Also note that for any **eigenvector** $x \in \mathbb{C}^n$, and scalar $t \in \mathbb{C}, A(cx) = cAx = c\lambda x = \lambda(cx)$, so $cx$ is also an **eigenvector**. For this reason when we talk about **“the” eigenvector** associated with $\lambda$, we usually assume that the **eigenvector** is normalized to have length $1$ (this still creates some ambiguity, since $x$ and $−x$ will both be **eigenvectors**, but we will have to live with this).

We can write all the eigenvector equations simultaneously as:
$A X = X \Lambda$
where the columns of $X \in \mathbb{R}^{n\times n}$ are the eigenvectors of $A$ and $\Lambda$ is a diagonal matrix whose entries are the eigenvalues of $A$:
    
$X \in \mathbb{R}^{n\times n} = \begin{bmatrix}
 \big| & \big| &  & \big| \\[0.3em]
 x_1 & x_2 & \cdots & x_n \\[0.3em]
 \big| & \big| &  & \big|  
\end{bmatrix} , \Lambda = \mathrm{diag}(\lambda_1, \dots{}, \lambda_n)$

If the eigenvectors of $A$ are linearly independent, then the matrix $X$ will be invertible, so $A = X \Lambda X^{−1}$. A matrix that can be written in this form is called **diagonalizable**.

In [59]:
from numpy import linalg

A = np.array([[ 2., 1. ],
              [ 1., 2. ]])
A

array([[2., 1.],
       [1., 2.]])

In [62]:
import scipy

In [64]:
v, U = np.linalg.eig(A)
print(v)
print(U)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [65]:
U@U.T

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

In [66]:
U@np.diag([3,1])@U.T

array([[2., 1.],
       [1., 2.]])

In [34]:
U.T@A@U

array([[ 3.00000000e+00, -4.39088730e-17],
       [ 2.23711432e-17,  1.00000000e+00]])

## Using Pytorch

In [67]:
import torch

# Check if MPS is available
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("MPS device found!")
else:
    print("MPS device not available.")

MPS device found!


In [68]:
tensor_a = torch.randn(10, 20, 30, device=device)
tensor_b = torch.randn(10, 30, 40, device=device)

In [69]:
%%time
result = torch.bmm(tensor_a, tensor_b) 

CPU times: user 950 µs, sys: 326 µs, total: 1.28 ms
Wall time: 627 µs


In [70]:
device = torch.device("cpu")
tensor_a = torch.randn(10, 20, 30, device=device)
tensor_b = torch.randn(10, 30, 40, device=device)

In [71]:
%%time
result = torch.bmm(tensor_a, tensor_b) 

CPU times: user 605 µs, sys: 260 µs, total: 865 µs
Wall time: 562 µs


## Quantum Mechanics and Linear Algebra

### **Wave Functions in function notation**
- **Definition**: A wave function $\psi(x,t)$ represents the quantum state of a particle. 
- **Probability density**: $|\psi(x,t)|^2 \, dx$ the probability of fing the particle in small volume $dx$ centered at $x$
- **Normalization**:
  $
  \int |\psi(x,t)|^2 \, dx = 1
  $
  



### **Momentum and Energy Operators**
- **Position Operator**:
  $
  \hat{x} = x
  $
- **Momentum Operator**:
  $
  \hat{p} = -i\hbar \frac{\partial}{\partial x}
  $
- **Kinetic energy Operator**:
  $
  \hat{T} = \dfrac{\hat{p}^2}{2m} = -\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2}
  $
- **Potential energy Operator**:
  $
  \hat{U} = U(x)
  $
- **Hamiltonian Operator**:
  $
  \hat{H} = \hat{T} + \hat{U} = -\frac{\hbar^2}{2m} \frac{\partial^2}{\partial x^2} + U(x)
  $

### Wave Function in Dirac notation
- Bra-ket notation: 
- $ |\psi\rangle $ is like a vector
- **Superposition**:
  $
  | \psi(x,t)\rangle = c_1 |\psi_1(x,t)\rangle + c_2 |\psi_2(x,t)\rangle
  $

###  **Time-Dependent Schrödinger Equation**:
  $
  i\hbar \frac{\partial |\psi(x,t)\rangle}{\partial t} = \hat{H} |\psi(x,t)\rangle
  $
  
###  **Time-Independent Schrödinger Equation**:
  $
  \hat{H} |\psi(x)\rangle = E |\psi(x)\rangle
  $
  


We focus on time-independent Schrödinger equation, because
- Simpler!
- Born-Oppenheimer approximation (electrons are fast)
- If $|\psi \rangle$ is an eigenstate of $\hat{H}$, 

$\hat{H} |\psi(x)\rangle = E |\psi(x)\rangle$

  $
  i\hbar \frac{\partial |\psi(x,t)\rangle}{\partial t} = E |\psi(x,t)\rangle
  $
  
  $
  |\psi(x,t)\rangle = \exp{(i\hbar E t)} |\psi(x,0)\rangle
  $
  
  An obervable $O$ at time $t$ doesn't change over time:
  $
  \langle \psi(t)|\hat{O}|\psi(t)\rangle = \langle \psi(0)|\hat{O}|\psi(0)\rangle
  $



###  **Matrix Representation**
- **State Vectors and Operator Matrices**:
  States are vectors $ |\psi\rangle $, and operators are matrices $ \hat{A} $.
- **Basis States**:
  $
  |\psi\rangle = \sum_i c_i |i\rangle
  $
  This is a column vector $c = [c_0, c_1, \ldots]^T$
- **Operator Matrix Elements**:
  $
  A_{ij} = \langle i|\hat{A}|j\rangle
  $
- **Full Matrix Representation**:
  Consider a simple two-state system with basis states $ |1\rangle $ and $ |2\rangle $. An operator $ \hat{A} $ might be represented as:
  $
  \hat{A} = \begin{bmatrix}
  \langle 1|\hat{A}|1\rangle & \langle 1|\hat{A}|2\rangle \\
  \langle 2|\hat{A}|1\rangle & \langle 2|\hat{A}|2\rangle
  \end{bmatrix}
  $
  If $ \hat{A} $ were the Hamiltonian $ \hat{H} $ in a simple model, its matrix elements could involve kinetic and potential energy terms specific to each state.
- **Diagonalization**:
  Diagonalizing the Hamiltonian matrix $ \hat{H} $:
  $
  \begin{bmatrix}
  H_{11} & H_{12} \\
  H_{21} & H_{22}
  \end{bmatrix}
  $
  leads to eigenvalues (energy levels) and eigenvectors (quantum states).


The Time-Independent Schrödinger Equation becomes:
$$
H c = E c
$$